Fastpass create: don't fail if project already exists
scalameta/fastpass pull request #51
Opened 2020-10-29 12:03 UTC by tpasternak

Prevously, `fastpass create --intellij <target>` was failing if the BSP
workspace was already existing. Now it does not fail and opens IDE, in the
same way as it was doing previously for newly created BSP workspaces.

2020-11-05 08:05 UTC, olafurpg requested changes
I think we should keep the old behavior when the user did not run `--intellij` or `--vscode`.

2020-11-05 08:05 UTC, olafurpg commented on fastpass/src/main/scala/scala/meta/internal/fastpass/pantsbuild/commands/CreateCommand.scala
> +        if (create.open.intellij) {
```suggestion
        if (!create.open.isEmpty) {
          create.open.run(...)
        } else {
          app.error("can't create ... <old message>")
        }
```

2020-11-05 08:05 UTC, olafurpg commented on fastpass/src/main/scala/scala/meta/internal/fastpass/pantsbuild/commands/CreateCommand.scala
> +          IntelliJ.launch(value, OpenOptions.default)
We should try to reuse this logic from OpenCommand

2020-11-05 08:05 UTC, olafurpg commented on fastpass/src/main/scala/scala/meta/internal/fastpass/pantsbuild/commands/CreateCommand.scala
> +        if (create.open.intellij) {
A bit confusing that I used "suggested changes", it was only meant as a rough draft

2020-11-06 10:54 UTC, tpasternak commented
@olafurpg CI is green now, but I had to change cache keys because it looks like the old cache was invalid, probably due to some system changes in GitHub Actions.

2020-11-28 11:40 UTC, tpasternak commented
@olafurpg could we merge this now?

2020-12-01 07:00 UTC, olafurpg approved these changes

2020-12-01 07:00 UTC, merged