Initial implementation of Fastpass for Bazel
scalameta/fastpass pull request #78
Opened 2022-05-17 14:51 UTC by Duhemm

This commit implements a port of Fastpass that creates Bloop projects
based on a Bazel build.

2022-05-19 01:41 UTC, wiwa requested changes
I started with a couple nits, but is it possible to split this PR into:  

1. Changes to the build / `.yml` files  
2. Addition of Bazel protobuf defs
3. Refactorings (e.g. seems like you refactored `BloopPants`) 
4. Additions to the logic for Bazel

Not sure how much effort it would take though, so not exactly a demand.

2022-05-19 04:23 UTC, Duhemm commented on fastpass/src/main/scala/scala/meta/internal/fastpass/IO.scala
> +  def toFileName(
Turns out it wasn't used anymore 🎉

2022-05-19 04:24 UTC, Duhemm commented on fastpass/src/main/scala/scala/meta/internal/fastpass/IO.scala
> +  def makeReadableFilename(target: String): String = {
It's just moving code from the previous BloopPants. It'd prefer to keep it like it is at the moment if you don't mind.

2022-05-19 04:27 UTC, Duhemm commented on fastpass/src/main/scala/scala/meta/internal/fastpass/IO.scala
> +  def toFileName(
It was used actually. Weird. I changed it!

2022-05-20 03:45 UTC, wiwa approved these changes
LGTM as far as I can tell at least. Thanks!

2022-05-20 03:45 UTC, wiwa commented on fastpass/src/main/scala/scala/meta/internal/fastpass/IO.scala
> +  def makeReadableFilename(target: String): String = {
Yep that's fine.

2022-05-20 03:45 UTC, wiwa commented on fastpass/src/main/scala/scala/meta/internal/fastpass/bazelbuild/ActionGraph.scala
> +      if mnemonics.contains(action.getMnemonic())
`mnemonics.get(action).map(transitiveInputsOf).getOrElse(Nil)`? I'm surprised that this actually compiles... does it desugar to just a `filter`? If so, it's fine if you leave it. On the other hand, the `for` comp can be in `Option` and the `getOrElse` could be in the end.

2022-05-25 08:04 UTC, merged